// <auto-generated />
using BootCamp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BootCamp.Migrations
{
    [DbContext(typeof(Ctx))]
    [Migration("20200830085759_m02")]
    partial class m02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BootCamp.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArticleName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("SectionId")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("ArticleId");

                    b.HasIndex("AuthorName");

                    b.HasIndex("SectionId");

                    b.ToTable("Article","cm");
                });

            modelBuilder.Entity("BootCamp.Models.Author", b =>
                {
                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("AuthorMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorReview")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("AuthorName");

                    b.ToTable("Author","cm");
                });

            modelBuilder.Entity("BootCamp.Models.Section", b =>
                {
                    b.Property<string>("SectionId")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("SectionId");

                    b.ToTable("Section","cm");
                });

            modelBuilder.Entity("BootCamp.Models.Article", b =>
                {
                    b.HasOne("BootCamp.Models.Author", "Author")
                        .WithMany("Article")
                        .HasForeignKey("AuthorName");

                    b.HasOne("BootCamp.Models.Section", "Section")
                        .WithMany("Article")
                        .HasForeignKey("SectionId");
                });
#pragma warning restore 612, 618
        }
    }
}
